#pragma once

#include <stdint.h>

namespace DX9VTable
{
#if _WIN64
    typedef uint64_t tableEntry;
#else
    typedef uint32_t tableEntry;
#endif

    #pragma pack(push)
    #pragma pack(1)
    struct DX9VTable
    {
        tableEntry QueryInterface; //[0]   
        tableEntry AddRef; //[1]   
        tableEntry Release; //[2]   
        tableEntry TestCooperativeLevel; //[3]   
        tableEntry GetAvailableTextureMem; //[4]   
        tableEntry EvictManagedResources; //[5]   
        tableEntry GetDirect3D; //[6]   
        tableEntry GetDeviceCaps; //[7]   
        tableEntry GetDisplayMode; //[8]   
        tableEntry GetCreationParameters; //[9]   
        tableEntry SetCursorProperties; //[10]  
        tableEntry SetCursorPosition; //[11]  
        tableEntry ShowCursor; //[12]  
        tableEntry CreateAdditionalSwapChain; //[13]  
        tableEntry GetSwapChain; //[14]  
        tableEntry GetNumberOfSwapChains; //[15]  
        tableEntry Reset; //[16]  
        tableEntry Present; //[17]  
        tableEntry GetBackBuffer; //[18]  
        tableEntry GetRasterStatus; //[19]  
        tableEntry SetDialogBoxMode; //[20]  
        tableEntry SetGammaRamp; //[21]  
        tableEntry GetGammaRamp; //[22]  
        tableEntry CreateTexture; //[23]  
        tableEntry CreateVolumeTexture; //[24]  
        tableEntry CreateCubeTexture; //[25]  
        tableEntry CreateVertexBuffer; //[26]  
        tableEntry CreateIndexBuffer; //[27]  
        tableEntry CreateRenderTarget; //[28]  
        tableEntry CreateDepthStencilSurface; //[29]  
        tableEntry UpdateSurface; //[30]  
        tableEntry UpdateTexture; //[31]  
        tableEntry GetRenderTargetData; //[32]  
        tableEntry GetFrontBufferData; //[33]  
        tableEntry StretchRect; //[34]  
        tableEntry ColorFill; //[35]  
        tableEntry CreateOffscreenPlainSurface; //[36]  
        tableEntry SetRenderTarget; //[37]  
        tableEntry GetRenderTarget; //[38]  
        tableEntry SetDepthStencilSurface; //[39]  
        tableEntry GetDepthStencilSurface; //[40]  
        tableEntry BeginScene; //[41]  
        tableEntry EndScene; //[42]  
        tableEntry Clear; //[43]  
        tableEntry SetTransform; //[44]  
        tableEntry GetTransform; //[45]  
        tableEntry MultiplyTransform; //[46]  
        tableEntry SetViewport; //[47]  
        tableEntry GetViewport; //[48]  
        tableEntry SetMaterial; //[49]  
        tableEntry GetMaterial; //[50]  
        tableEntry SetLight; //[51]  
        tableEntry GetLight; //[52]  
        tableEntry LightEnable; //[53]  
        tableEntry GetLightEnable; //[54]  
        tableEntry SetClipPlane; //[55]  
        tableEntry GetClipPlane; //[56]  
        tableEntry SetRenderState; //[57]  
        tableEntry GetRenderState; //[58]  
        tableEntry CreateStateBlock; //[59]  
        tableEntry BeginStateBlock; //[60]  
        tableEntry EndStateBlock; //[61]  
        tableEntry SetClipStatus; //[62]  
        tableEntry GetClipStatus; //[63]  
        tableEntry GetTexture; //[64]  
        tableEntry SetTexture; //[65]  
        tableEntry GetTextureStageState; //[66]  
        tableEntry SetTextureStageState; //[67]  
        tableEntry GetSamplerState; //[68]  
        tableEntry SetSamplerState; //[69]  
        tableEntry ValidateDevice; //[70]  
        tableEntry SetPaletteEntries; //[71]  
        tableEntry GetPaletteEntries; //[72]  
        tableEntry SetCurrentTexturePalette; //[73]  
        tableEntry GetCurrentTexturePalette; //[74]  
        tableEntry SetScissorRect; //[75]  
        tableEntry GetScissorRect; //[76]  
        tableEntry SetSoftwareVertexProcessing; //[77]  
        tableEntry GetSoftwareVertexProcessing; //[78]  
        tableEntry SetNPatchMode; //[79]  
        tableEntry GetNPatchMode; //[80]  
        tableEntry DrawPrimitive; //[81]  
        tableEntry DrawIndexedPrimitive; //[82]  
        tableEntry DrawPrimitiveUP; //[83]  
        tableEntry DrawIndexedPrimitiveUP; //[84]  
        tableEntry ProcessVertices; //[85]  
        tableEntry CreateVertexDeclaration; //[86]  
        tableEntry SetVertexDeclaration; //[87]  
        tableEntry GetVertexDeclaration; //[88]  
        tableEntry SetFVF; //[89]  
        tableEntry GetFVF; //[90]  
        tableEntry CreateVertexShader; //[91]  
        tableEntry SetVertexShader; //[92]  
        tableEntry GetVertexShader; //[93]  
        tableEntry SetVertexShaderConstantF; //[94]  
        tableEntry GetVertexShaderConstantF; //[95]  
        tableEntry SetVertexShaderConstantI; //[96]  
        tableEntry GetVertexShaderConstantI; //[97]  
        tableEntry SetVertexShaderConstantB; //[98]  
        tableEntry GetVertexShaderConstantB; //[99]  
        tableEntry SetStreamSource; //[100] 
        tableEntry GetStreamSource; //[101] 
        tableEntry SetStreamSourceFreq; //[102] 
        tableEntry GetStreamSourceFreq; //[103] 
        tableEntry SetIndices; //[104] 
        tableEntry GetIndices; //[105] 
        tableEntry CreatePixelShader; //[106] 
        tableEntry SetPixelShader; //[107] 
        tableEntry GetPixelShader; //[108] 
        tableEntry SetPixelShaderConstantF; //[109] 
        tableEntry GetPixelShaderConstantF; //[110] 
        tableEntry SetPixelShaderConstantI; //[111] 
        tableEntry GetPixelShaderConstantI; //[112] 
        tableEntry SetPixelShaderConstantB; //[113] 
        tableEntry GetPixelShaderConstantB; //[114] 
        tableEntry DrawRectPatch; //[115] 
        tableEntry DrawTriPatch; //[116] 
        tableEntry DeletePatch; //[117] 
        tableEntry CreateQuery; //[118] 
    };
    #pragma pack(pop)

}